### ISSUE TITLE
Choose Structure for Database

### ISSUE THREAD

**Issue by puigabreu** [uprm-inso-4115-2020-2021-s2/semester-project-schutzies#3]
Research and choose a structure for the database. 

References for tech stack:
-

Acceptance Criteria:
-
- Be able to present and explain tech stack choices to group.

**Comment by hiramGL** [comment]
**MongoDB Suggestion**
Theo, a traves de todos los distintos cursos que he visto veo que cuando hay cursos o tutoriales sobre database utilizando Nodejs hablan muhco de MongoDB, no los he visto todavia porque todavia no me siento proficient con nodejs como para bregar con db pero lo comparto un link de un website que estoy usando para aprender de nodejs y de javascript.
https://www.youtube.com/watch?v=b91XgdyX-SM

**Comment by puigabreu** [comment]
We have agreed to choose MongoDB as our database.
