### ISSUE TITLE
Proposal - Implementation Part (BackEnd)

### ISSUE THREAD

**Issue by YaritzaGarcia** [uprm-inso-4115-2020-2021-s2/semester-project-schutzies#6]
Mention what technologies are going to be used (Frameworks, programming languages, libraries, etc.) and say why these technologies are going to be used.

**Google Drive Doc:** https://docs.google.com/document/d/1EetI6grKwaaP0mkuUYY6oebXOcoNpQW8YloH2nmWEiY/edit?usp=sharing

**Comment by puigabreu** [comment]
Both @hiramGL and I have detailed the back-end technologies (SailsJS) and the database structure (MongoDB) in the document draft.
